### ISSUE TITLE
Augmentation is failing in almond-cloud staging

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#111]
```
TypeError: Cannot read property 'schema' of null
at ParameterReplacer._getParamListKey (/opt/almond-cloud/node_modules/genie-toolkit/lib/replace_parameters.js:224:26)
at ParameterReplacer._sampleParam (/opt/almond-cloud/node_modules/genie-toolkit/lib/replace_parameters.js:282:39)
at ParameterReplacer._replaceTokensInSentence (/opt/almond-cloud/node_modules/genie-toolkit/lib/replace_parameters.js:376:44)
at promises.push (/opt/almond-cloud/node_modules/genie-toolkit/lib/replace_parameters.js:534:54)
at ParameterReplacer.process (/opt/almond-cloud/node_modules/genie-toolkit/lib/replace_parameters.js:560:15)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gcampax** [comment]
Failure case:
Sentence:
"if any websites match the specialties in my linkedin profile and are not the title QUOTED_STRING_0 notify me"
Code:
`edge ( monitor ( ( @com.linkedin.get_profile ) join ( @com.bing.web_search ) on param:query:String = param:specialties:String ) ) on not param:title:String == QUOTED_STRING_0 => notify`
