### ISSUE TITLE
Possible error in genie.js

### ISSUE THREAD

**Issue by anuragkumar95** [stanford-oval/genie-toolkit#327]
The command ```genie generate --help``` throws a syntax error,

```
(genie-anurag) anurag@deepbox:~/genie-toolkit$ genie generate --help
/home/anurag/genie-toolkit/node_modules/argparse/argparse.js:223
    } catch {}
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/anurag/genie-toolkit/tool/genie.js:23:18)
```

Any possible fixes for this?

**Comment by gcampax** [comment]
Oh wow. That error is in a dependency, "argparse", not in our code. It's using a syntax that I've never seen, so it must be a recent addition to JS. But I can tell you it works with nodejs 10.*, which is the minimum version we support. What version of node do you have?

**Comment by anuragkumar95** [comment]
```
(genie-anurag) anurag@deepbox:~/genie-toolkit$ node --version
v10.22.0
```

**Comment by gcampax** [comment]
Are you sure that's the version of node being used? Do you have multiple versions installed?
What if you change the she-bang in tool/genie.js to be `#!/usr/bin/env node` ?

**Comment by anuragkumar95** [comment]
It is fixed. Thanks!
