### ISSUE TITLE
Error in thingpedia datasets download

### ISSUE THREAD

**Issue by anuragkumar95** [stanford-oval/genie-toolkit#328]
/doc/tutorial-basic.md 

If you have an appropriate Thingpedia developer key, you can also download the datasets with:
```
thingpedia download-entity-values -d parameter-datasets/ --manifest parameter-datasets.tsv
thingpedia download-string-values -d parameter-datasets/ --manifest parameter-datasets.tsv --append-manifest 
```
My developer key is "dev_key" that I received from almond developer website. 
I can successfully execute the 1st command
```
(genie-anurag) anurag@deepbox:~/genie-toolkit$ thingpedia --access-token ABC --url https://thingpedia.stanford.edu/thingpedia --developer-key dev_key download-entity-values -d parameter-datasets/ --manifest parameter-datasets.tsv
100%  [==============================] - 31s
```
 While the 2nd command throws an error:
```
(genie-anurag) anurag@deepbox:~/genie-toolkit$ thingpedia --access-token ABC --url https://thingpedia.stanford.edu/thingpedia --developer-key dev_key download-string-values -d parameter-datasets/ --manifest parameter-datasets.tsv --append-manifest
  0%  [..............................] - ETA: 0sHTTP request failed: {"error":"A valid developer key is required to download string datasets","code":"EPERM"}
{ Error: Unexpected HTTP error 403
    at IncomingMessage.res.on (/home/anurag/.config/yarn/global/node_modules/thingpedia/lib/helpers/http.js:111:33)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  detail:
   '{"error":"A valid developer key is required to download string datasets","code":"EPERM"}',
  code: 403 }
```

Am I missing something?

**Comment by gcampax** [comment]
You got your account from almond-dev.stanford.edu but you're passing thingpedia.stanford.edu as the URL. Those two need to match.
