### ISSUE TITLE
Training genienlp

### ISSUE THREAD

**Issue by anuragkumar95** [stanford-oval/genie-toolkit#330]
OUTDIR and WORKDIR are directories inside the git repo genie-toolkit. Am I missing anything here?

```
(genie-anurag) anurag@deepbox:~/genie-toolkit$ genie train --datadir ~/genie-toolkit --outputdir ~/genie-toolkit/OUTDIR --workdir ~/genie-toolkit/WORKDIR --config-file data/bert-lstm-single-sentence.json --debug
(node:5948) DeprecationWarning: _SubParsersAction.addParser() is renamed to _SubParsersAction.add_parser()
(node:5948) DeprecationWarning: add_parser(): following options are renamed: 'addHelp' -> 'add_help'
(node:5948) DeprecationWarning: _ActionsContainer.addArgument() is renamed to _ActionsContainer.add_argument()
genienlp 'train' '--train_tasks' 'almond' '--save' '/home/anurag/genie-toolkit/WORKDIR/model' '--cache' '/home/anurag/genie-toolkit/WORKDIR/cache' '--data' '/home/anurag/genie-toolkit/WORKDIR' '--preserve_case' '--embeddings' '/home/anurag/genie-toolkit/WORKDIR/embeddings' '--train_iterations' '100000' '--save_every' '2000' '--log_every' '500' '--val_every' '1000' '--train_batch_tokens' '4000' '--val_batch_size' '128' '--seq2seq_encoder' 'Identity' '--dimension' '768' '--rnn_dimension' '768' '--transformer_hidden' '768' '--transformer_layers' '0' '--rnn_layers' '2' '--rnn_zero_state' 'average' '--context_embeddings' 'bert-base-uncased@0' '--question_embeddings' 'bert-base-uncased@1' '--decoder_embeddings' '' '--trainable_encoder_embeddings' '0' '--trainable_decoder_embeddings' '25' '--transformer_lr_multiply' '0.5' '--train_context_embeddings' '--train_context_embeddings_after' '80000'
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/anurag/anaconda3/envs/genie-anurag/bin/genienlp", line 8, in <module>
    sys.exit(main())
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/__main__.py", line 54, in main
    subcommands[argv.subcommand][2](argv)
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/train.py", line 526, in main
    args = arguments.post_parse(args)
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/arguments.py", line 281, in post_parse
    args.commit = get_commit()
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/arguments.py", line 45, in get_commit
    return subprocess.Popen("cd {} && git log | head -n 1".format(directory), shell=True,
IndexError: list index out of range
/home/anurag/genie-toolkit/tool/genie.js:21
process.on('unhandledRejection', (up) => { throw up; });
                                           ^

Error: Command exited with code 1
    at ChildProcess.child.on (/home/anurag/genie-toolkit/lib/training/exec-utils.js:67:28)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

**Comment by gcampax** [comment]
This bug occurs because you installed genienlp from pip instead of git, and the config file you use does not specify `"no_commit": true`.

Can you try PR #331 which should solve your problem?

**Comment by anuragkumar95** [comment]
I run into a different error message now,
```
 'val_task_names': ['almond'],
 'val_tasks': [<genienlp.tasks.almond.Almond object at 0x7f4eed906220>],
 'vocab_tasks': None,
 'warmup': 800,
 'weight_decay': 0.0}
genienlp.train - Loading almond
genienlp.train - Adding almond to training datasets
Traceback (most recent call last):
  File "/home/anurag/anaconda3/envs/genie-anurag/bin/genienlp", line 8, in <module>
    sys.exit(main())
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/__main__.py", line 54, in main
    subcommands[argv.subcommand][2](argv)
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/train.py", line 540, in main
    prepare_data(args, logger)
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/train.py", line 87, in prepare_data
    split = task.get_splits(args.data, lower=args.lower, **kwargs)
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/tasks/almond/__init__.py", line 145, in get_splits
    return AlmondDataset.return_splits(path=os.path.join(root, 'almond'), make_example=self._make_example, **kwargs)
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/tasks/almond/__init__.py", line 95, in return_splits
    train_data = None if train is None else cls(os.path.join(path, train + '.tsv'), **kwargs)
  File "/home/anurag/anaconda3/envs/genie-anurag/lib/python3.8/site-packages/genienlp/tasks/almond/__init__.py", line 65, in __init__
    with open(path, 'r', encoding='utf-8') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/anurag/genie-toolkit/WORKDIR/almond/train.tsv'
/home/anurag/genie-toolkit/tool/genie.js:21
process.on('unhandledRejection', (up) => { throw up; });
                                           ^

Error: Command exited with code 1
    at ChildProcess.child.on (/home/anurag/genie-toolkit/lib/training/exec-utils.js:67:28)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

It throws an error if ```WORKDIR``` already has a directory ```almond```. Should I copy the train.tsv file into WORKDIR? I don't see how I can do that.

**Comment by gcampax** [comment]
I think the datadir you're passing is incorrect. You need to pass a path to a folder that contains the dataset (train.tsv, eval.tsv). The command then sets up some symlinks in the workdir to point to the files in the datadir.

**Comment by anuragkumar95** [comment]
That worked! Although, it seems to give me CUDA memory error. Any tips to avoid this?

**Comment by gcampax** [comment]
You should probably reduce the training batch sizes ("train_batch_tokens") and validation batch sizes ("val_batch_size") in the config file. The current numbers are tuned to a V100 GPU with 16GB of VRAM.
