### ISSUE TITLE
Throws error for location not found

### ISSUE THREAD

**Issue by AshwinParanjape** [stanford-oval/genie-toolkit#389]
```
>> What location do you want the current weather for?
>> expecting: location
$ shashta mountains
Analyzed message into $dialogue @org.thingpedia.dialogue.transaction.execute ; now => @org.thingpedia.weather.current param:location = location: " shashta mountains " => notify ;
>> Sorry, I cannot find any location matching “shashta mountains”. What location are you looking for?
>> Sorry, I had an error processing your command: The expression evaluated to a falsy value:

  assert_1.default(item.confirm !== 'confirmed')
.
{ AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default(item.confirm !== 'confirmed')

    at Object.prepareContextForPrediction (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue_state_utils.js:192:25)
    at DialogueLoop.setExpected (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:374:48)
    at DialogueLoop.ask (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:385:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
Uncaught error in dialog loop { AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default(item.confirm !== 'confirmed')

    at Object.prepareContextForPrediction (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue_state_utils.js:192:25)
    at DialogueLoop.setExpected (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:374:48)
    at DialogueLoop.nextQueueItem (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:291:14)
    at DialogueLoop._loop (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:253:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/tool/genie.js:40
process.on('unhandledRejection', (up) => { throw up; });
                                           ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default(item.confirm !== 'confirmed')

    at Object.prepareContextForPrediction (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue_state_utils.js:192:25)
    at DialogueLoop.setExpected (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:374:48)
    at DialogueLoop.nextQueueItem (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:291:14)
    at DialogueLoop._loop (/Users/ashwinparanjape/research/zoo/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:253:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gcampax** [comment]
Fixed by #443
