### ISSUE TITLE
Dataset generation command from README crashes

### ISSUE THREAD

**Issue by cpchen** [stanford-oval/genie-toolkit#391]
I tried running `make experiment=restaurants maxdepth=5 target_pruning_size=500 datadir` as described in https://github.com/stanford-oval/genie-toolkit/tree/master/starter/schemaorg#generate-a-dataset

and got the following error at the point of this `node` command:

```
node --experimental_worker --max_old_space_size=15000 ../../tool/genie.js augment -o restaurants/augmented.tsv.tmp -l en-US --thingpedia restaurants/manifest.tt --parameter-datasets restaurants/parameter-datasets.tsv \
          --synthetic-expand-factor 1 --quoted-paraphrasing-expand-factor 60 --no-quote-paraphrasing-expand-factor 20 --quoted-fraction 0.0 \
          --debug  restaurants/synthetic.tsv
Found no argument property for compute.expression.distance.1:Location
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/penc/genie-toolkit/starter/schemaorg/restaurants/shared-parameter-datasets/tt:location.tsv'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:147:14
    at FSReqCallback.oncomplete (fs.js:164:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/penc/genie-toolkit/starter/schemaorg/restaurants/shared-parameter-datasets/tt:location.tsv'
}
make: *** [restaurants/augmented.tsv] Error 1
```

It looks like `shared-parameter-datasets` should actually be one directory level up?

**Comment by gcampax** [comment]
Hello! What branch is this? And where are you running the `make` command? It should run from inside the "schemaorg" folder, not inside the subfolder.

**Comment by cpchen** [comment]
This is on master and I am running it on the schemaorg folder.

**Comment by gcampax** [comment]
Are you on OS X by any chance? (or another BSD-like OS). I learned today that sed behaves differently on OS X, you might want to try #392

**Comment by cpchen** [comment]
I am on OSX but I still get the same error:

```➜  schemaorg git:(wip/fix-sed) ✗ make experiment=restaurants maxdepth=5 target_pruning_size=500 datadir

node --experimental_worker --max_old_space_size=15000 ../../tool/genie.js augment -o restaurants/augmented.tsv.tmp -l en-US --thingpedia restaurants/manifest.tt --parameter-datasets restaurants/parameter-datasets.tsv \
          --synthetic-expand-factor 1 --quoted-paraphrasing-expand-factor 60 --no-quote-paraphrasing-expand-factor 20 --quoted-fraction 0.0 \
          --debug  restaurants/synthetic.tsv
Found no argument property for compute.expression.distance.1:Location
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/penc/genie-toolkit/starter/schemaorg/restaurants/shared-parameter-datasets/tt:location.tsv'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:147:14
    at FSReqCallback.oncomplete (fs.js:164:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/penc/genie-toolkit/starter/schemaorg/restaurants/shared-parameter-datasets/tt:location.tsv'
}```

**Comment by gcampax** [comment]
Make sure you clean the directory with `git clean -fdx` before trying again, otherwise the parameter-datasets.tsv file will not be remade and will still contain the bug.

**Comment by gcampax** [comment]
Closing this. Please reopen if you still experience the issue with the latest version of genie-toolkit.
