### ISSUE TITLE
Weather skill throws exception

### ISSUE THREAD

**Issue by s-jse** [stanford-oval/genie-toolkit#462]
This doesn't seem like a parser mistake.
Full conversation:
```
Almond: Hello! How can I help you?
User: what is the weather
Almond: Sorry, I had an error processing your command: Invalid parameter types Enum(raining,cloudy,sunny,snowy,sleety,drizzling,windy), Enum(raining,cloudy,sunny,snowy,sleety,drizzling,windy,foggy) for ==.
```
Full log:

```
2/10/2021, 3:58:16 PM: Initializing dialogue policy for devices:
2/10/2021, 3:58:16 PM: --- DEPTH 0
2/10/2021, 3:58:16 PM: depth 0 took 0.00 seconds
2/10/2021, 3:58:16 PM: --- DEPTH 1
2/10/2021, 3:58:16 PM: depth 1 took 0.00 seconds
2/10/2021, 3:58:16 PM: --- DEPTH 2
2/10/2021, 3:58:16 PM: depth 2 took 0.00 seconds
2/10/2021, 3:58:16 PM: --- DEPTH 3
2/10/2021, 3:58:16 PM: depth 3 took 0.00 seconds
2/10/2021, 3:58:16 PM: --- DEPTH 4
2/10/2021, 3:58:16 PM: depth 4 took 0.00 seconds
2/10/2021, 3:58:16 PM: --- DEPTH 5
2/10/2021, 3:58:16 PM: depth 5 took 0.00 seconds
2/10/2021, 3:58:16 PM: --- DEPTH 6
2/10/2021, 3:58:16 PM: depth 6 took 0.00 seconds
2/10/2021, 3:58:16 PM: --- DEPTH 7
2/10/2021, 3:58:16 PM: depth 7 took 0.00 seconds
2/10/2021, 3:58:31 PM: Analyzed message into @org.thingpedia.weather . current ( ) ;
2/10/2021, 3:58:31 PM: Batched dataset request for org.thingpedia.weather
2/10/2021, 3:58:31 PM: TypeError: Invalid parameter types Enum(raining,cloudy,sunny,snowy,sleety,drizzling,windy), Enum(raining,cloudy,sunny,snowy,sleety,drizzling,windy,foggy) for ==
2/10/2021, 3:58:31 PM: at TypeChecker._resolveOverload (/opt/thingengine/node_modules/thingtalk/dist/typecheck.js:325:15)
2/10/2021, 3:58:31 PM: at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gcampax** [comment]
I cannot reproduce this on my account. Is that the latest version of the weather skill (version 9)?
