### ISSUE TITLE
TTS errors crash Almond

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#536]
Logs:
```
Genie says: I played music by Sara Bareilles on Spotify for you.
HTTP request failed: {"error":"Internal Server Error","code":"ENOTFOUND"}
/opt/almond/main.js:24
process.on('unhandledRejection', (up) => { throw up; });
                                           ^
HTTPError: Unexpected HTTP error 500 in request to https://almond-nl.stanford.edu/en-US/voice/tts
    at IncomingMessage.<anonymous> (/opt/almond/node_modules/thingpedia/dist/helpers/http.js:134:35)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 500,
  url: 'https://almond-nl.stanford.edu/en-US/voice/tts',
  detail: '{"error":"Internal Server Error","code":"ENOTFOUND"}'
}
```

**Comment by gcampax** [comment]
The underlying error in almond-cloud, for posterity:
```
{ Error: getaddrinfo ENOTFOUND westus2.api.cognitive.microsoft.com westus2.api.cognitive.microsoft.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'westus2.api.cognitive.microsoft.com',
  host: 'westus2.api.cognitive.microsoft.com',
  port: 443 }
  ```
  
  Seems to be a transient DNS issue.
