### ISSUE TITLE
Cannot run basic sentence generation after installing

### ISSUE THREAD

**Issue by ssiu** [stanford-oval/genie-toolkit#539]
I followed the 'git' install guide here https://github.com/stanford-oval/genie-toolkit/blob/master/doc/install.md, downloaded the three files `thingpedia.tt`, `dataset.tt` and `entities.json`. When I run the command 
```
genie generate --locale en-US --template languages/thingtalk/en/thingtalk.genie
  --thingpedia thingpedia.tt --entities entities.json --dataset dataset.tt
  -o synthesized.tsv
```
I got this error
```
  0%  [..............................] - ETA: 0sError: Cannot find module '../ast_manip'
Require stack:
- /mnt/shared_ad3_mt1/swsiu/genie-toolkit/languages/thingtalk/en/thingtalk.genie.js
- /mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/lib/sentence-generator/compiler/index.js
- /mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/compile-template.js
- /mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/genie.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/shared_ad3_mt1/swsiu/genie-toolkit/languages/thingtalk/en/thingtalk.genie.js:44:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/shared_ad3_mt1/swsiu/genie-toolkit/languages/thingtalk/en/thingtalk.genie.js',
    '/mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/lib/sentence-generator/compiler/index.js',
    '/mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/compile-template.js',
    '/mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/genie.js'
  ]
}
/mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/genie.js:40
process.on('unhandledRejection', (up) => { throw up; });
                                           ^

Error: Cannot find module '../ast_manip'
Require stack:
- /mnt/shared_ad3_mt1/swsiu/genie-toolkit/languages/thingtalk/en/thingtalk.genie.js
- /mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/lib/sentence-generator/compiler/index.js
- /mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/compile-template.js
- /mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/genie.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/shared_ad3_mt1/swsiu/genie-toolkit/languages/thingtalk/en/thingtalk.genie.js:44:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
Emitted 'error' event on BasicSentenceGenerator instance at:
    at /mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/lib/sentence-generator/batch.js:96:18 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/shared_ad3_mt1/swsiu/genie-toolkit/languages/thingtalk/en/thingtalk.genie.js',
    '/mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/lib/sentence-generator/compiler/index.js',
    '/mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/compile-template.js',
    '/mnt/shared_ad3_mt1/swsiu/genie-toolkit/dist/tool/genie.js'
  ]
}
```
I would be glad if you could help me with this. Thanks!

**Comment by gcampax** [comment]
I think the guide needs to be updated, sorry. The command should be:
```
genie generate --locale en-US --template languages-dist/thingtalk/en/thingtalk.genie
  --thingpedia thingpedia.tt --entities entities.json --dataset dataset.tt
  -o synthesized.tsv
```
(note "languages-dist" instead of "languages")
Because you need to refer to the compiled version of the templates, not the source version, if you don't use ts-node.

Let me know if this works!

**Comment by ssiu** [comment]
Great it works now, thank you so much!
