### ISSUE TITLE
Unexpected default unit defaultTemperature

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#609]
Reported by @almakantara 

Log:
```
Received assistant command 30 degrees Celsius.
Confidently analyzed message into $dialogue @org.thingpedia.dialogue.transaction.execute;
@org.thingpedia.iot.climate(id="io.home-assistant/http://192.168.0.200:8123/climate.office"^^tt:device_id("Office Thermostat")).set_target_temperature(value=30defaultTemperature);
Genie says: Sorry, I had an error processing your command: Unexpected default unit defaultTemperature.
Starting to speak...
TypeError: Unexpected default unit defaultTemperature
    at ExecutionDialogueAgent._concretizeValue (/home/user/oval/almond/almond-server/node_modules/genie-toolkit/dist/lib/dialogue-agent/abstract_dialogue_agent.js:334:31)
    at ExecutionDialogueAgent._prepareForExecution (/home/user/oval/almond/almond-server/node_modules/genie-toolkit/dist/lib/dialogue-agent/abstract_dialogue_agent.js:225:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionDialogueAgent.execute (/home/user/oval/almond/almond-server/node_modules/genie-toolkit/dist/lib/dialogue-agent/abstract_dialogue_agent.js:126:13)
    at async DialogueLoop._executeCurrentState (/home/user/oval/almond/almond-server/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:530:81)
    at async DialogueLoop._handleNormalDialogueCommand (/home/user/oval/almond/almond-server/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:524:9)
    at async DialogueLoop._handleUserInput (/home/user/oval/almond/almond-server/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:503:21)
    at async DialogueLoop._loop (/home/user/oval/almond/almond-server/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:600:21)
```

**Comment by gcampax** [comment]
(There is also a slightly different bug in that "30 degrees celsius" should be parsed as 30C not 30defaultTemperature - we probably need additional templates for that)
