### ISSUE TITLE
Fails to compute a reply to "currently playing" question

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#668]
```
$dialogue @org.thingpedia.dialogue.transaction.execute;
[artists] of @com.spotify(id="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax")).get_currently_playing()
#[results=[
  { id="spotify:track:67lbzVADsqJJ6tyVk0XCgn"^^com.spotify:song("Chain My Heart"), artists=["spotify:artist:0u6GtibW46tFX7koQ6uNJZ"^^com.spotify:artist("Topic"), "spotify:artist:64M6ah0SkkRsnPGtGiRAbb"^^com.spotify:artist("Bebe Rexha")] }
]];
Genie executed new program: uuid-28303eb8-9222-4899-9019-bf5fe73cba9e
--- DEPTH 0
stats: size(charts[0][constant_Number]) = 13
stats: size(charts[0][constant_String]) = 1
stats: size(charts[0][out_param_Any]) = 15
stats: size(charts[0][constant_Entity__com__spotify__artist]) = 2
stats: size(charts[0][constant_Entity__com__spotify__song]) = 1
stats: size(charts[0][constant_Enum__on__off]) = 2
stats: size(charts[0][constant_Enum__track__context__off]) = 3
stats: size(charts[0][ctx_with_result]) = 1
stats: size(charts[0][ctx_with_table_result]) = 1
stats: size(charts[0][ctx_without_action]) = 1
stats: size(charts[0][ctx_with_result_noquestion]) = 1
stats: size(charts[0][ctx_current_statement]) = 1
stats: size(charts[0][ctx_display_nonlist_result]) = 1
stats: size(charts[0][ctx_current_query]) = 1
stats: size(charts[0][ctx_thingpedia_result]) = 1
stats: size(charts[0][ctx_result_name]) = 1
depth 0 took 14 milliseconds

--- DEPTH 1
stats: size(charts[1][constant_Any]) = 22
stats: size(charts[1][actionable_system_display_result_short]) = 1
depth 1 took 1 milliseconds

--- DEPTH 2
stats: size(charts[2][one_param_direct_result_info_phrase]) = 1
depth 2 took 1 milliseconds

--- DEPTH 3
stats: size(charts[3][direct_result_info_phrase]) = 1
depth 3 took 2 milliseconds

--- DEPTH 4
depth 4 took 2 milliseconds

--- DEPTH 5
depth 5 took 1 milliseconds

--- DEPTH 6
depth 6 took 1 milliseconds

--- DEPTH 7
depth 7 took 0 milliseconds

--- DEPTH 8
depth 8 took 1 milliseconds

--- DEPTH 0
stats: size(charts[0][constant_Number]) = 13
stats: size(charts[0][constant_String]) = 1
stats: size(charts[0][out_param_Any]) = 41
stats: size(charts[0][constant_Entity__com__spotify__artist]) = 2
stats: size(charts[0][constant_Entity__com__spotify__song]) = 1
stats: size(charts[0][constant_Enum__on__off]) = 2
stats: size(charts[0][constant_Enum__track__context__off]) = 3
stats: size(charts[0][ctx_with_result]) = 1
stats: size(charts[0][ctx_with_table_result]) = 1
stats: size(charts[0][ctx_without_action]) = 1
stats: size(charts[0][ctx_with_result_noquestion]) = 1
stats: size(charts[0][ctx_current_statement]) = 1
stats: size(charts[0][ctx_display_nonlist_result]) = 1
stats: size(charts[0][ctx_current_query]) = 1
stats: size(charts[0][ctx_thingpedia_result]) = 1
stats: size(charts[0][ctx_result_name]) = 1
depth 0 took 14 milliseconds

--- DEPTH 1
stats: size(charts[1][constant_Any]) = 22
stats: size(charts[1][actionable_system_display_result_short]) = 1
depth 1 took 1 milliseconds

--- DEPTH 2
stats: size(charts[2][one_param_direct_result_info_phrase]) = 1
depth 2 took 1 milliseconds

--- DEPTH 3
stats: size(charts[3][direct_result_info_phrase]) = 1
depth 3 took 0 milliseconds

--- DEPTH 4
depth 4 took 1 milliseconds

--- DEPTH 5
depth 5 took 2 milliseconds

--- DEPTH 6
depth 6 took 0 milliseconds

--- DEPTH 7
depth 7 took 0 milliseconds

--- DEPTH 8
depth 8 took 1 milliseconds

--- DEPTH 0
stats: size(charts[0][constant_Number]) = 13
stats: size(charts[0][constant_String]) = 1
stats: size(charts[0][out_param_Any]) = 41
stats: size(charts[0][constant_Entity__com__spotify__artist]) = 2
stats: size(charts[0][constant_Entity__com__spotify__song]) = 1
stats: size(charts[0][constant_Enum__on__off]) = 2
stats: size(charts[0][constant_Enum__track__context__off]) = 3
stats: size(charts[0][ctx_with_result]) = 1
stats: size(charts[0][ctx_with_table_result]) = 1
stats: size(charts[0][ctx_without_action]) = 1
stats: size(charts[0][ctx_with_result_noquestion]) = 1
stats: size(charts[0][ctx_current_statement]) = 1
stats: size(charts[0][ctx_display_nonlist_result]) = 1
stats: size(charts[0][ctx_current_query]) = 1
stats: size(charts[0][ctx_thingpedia_result]) = 1
stats: size(charts[0][ctx_result_name]) = 1
depth 0 took 10 milliseconds

--- DEPTH 1
stats: size(charts[1][constant_Any]) = 22
stats: size(charts[1][actionable_system_display_result_short]) = 1
depth 1 took 0 milliseconds

--- DEPTH 2
stats: size(charts[2][one_param_direct_result_info_phrase]) = 1
depth 2 took 1 milliseconds

--- DEPTH 3
stats: size(charts[3][direct_result_info_phrase]) = 1
depth 3 took 0 milliseconds

--- DEPTH 4
depth 4 took 1 milliseconds

--- DEPTH 5
depth 5 took 0 milliseconds

--- DEPTH 6
depth 6 took 1 milliseconds

--- DEPTH 7
depth 7 took 0 milliseconds

--- DEPTH 8
depth 8 took 0 milliseconds

--- DEPTH 0
stats: size(charts[0][constant_Number]) = 13
stats: size(charts[0][constant_String]) = 1
stats: size(charts[0][out_param_Any]) = 41
stats: size(charts[0][constant_Entity__com__spotify__artist]) = 2
stats: size(charts[0][constant_Entity__com__spotify__song]) = 1
stats: size(charts[0][constant_Enum__on__off]) = 2
stats: size(charts[0][constant_Enum__track__context__off]) = 3
stats: size(charts[0][ctx_with_result]) = 1
stats: size(charts[0][ctx_with_table_result]) = 1
stats: size(charts[0][ctx_without_action]) = 1
stats: size(charts[0][ctx_with_result_noquestion]) = 1
stats: size(charts[0][ctx_current_statement]) = 1
stats: size(charts[0][ctx_display_nonlist_result]) = 1
stats: size(charts[0][ctx_current_query]) = 1
stats: size(charts[0][ctx_thingpedia_result]) = 1
stats: size(charts[0][ctx_result_name]) = 1
depth 0 took 8 milliseconds

--- DEPTH 1
stats: size(charts[1][constant_Any]) = 22
stats: size(charts[1][actionable_system_display_result_short]) = 1
depth 1 took 1 milliseconds

--- DEPTH 2
stats: size(charts[2][one_param_direct_result_info_phrase]) = 1
depth 2 took 0 milliseconds

--- DEPTH 3
stats: size(charts[3][direct_result_info_phrase]) = 1
depth 3 took 0 milliseconds

--- DEPTH 4
depth 4 took 1 milliseconds

--- DEPTH 5
depth 5 took 0 milliseconds

--- DEPTH 6
depth 6 took 0 milliseconds

--- DEPTH 7
depth 7 took 0 milliseconds

--- DEPTH 8
depth 8 took 0 milliseconds

Genie says: Sorry, I had an error processing your command: Failed to compute a reply.
AssertionError [ERR_ASSERTION]: Failed to compute a reply
    at ThingTalkDialogueHandler._doAgentReply (/var/home/gcampagn/Projects/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/handlers/thingtalk.js:374:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DialogueLoop._handleUserInput (/var/home/gcampagn/Projects/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:308:27)
    at async DialogueLoop._loop (/var/home/gcampagn/Projects/thingpedia-common-devices/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:354:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
Invalid reply: Sorry, I had an error processing your command: Failed to compute a reply.
```

**Comment by gcampax** [comment]
Still occurring:
```
====
# main/894fa0c8-70fe-42e4-afe9-dfe1203404ee
#! timestamp: 2021-08-03T19:02:33.874Z
U: what is currently playing
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: @org.thingpedia.media-source.get_currently_playing();
C: $dialogue @org.thingpedia.dialogue.transaction.execute;
C: @org.thingpedia.media-source(id="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax")).get_currently_playing()
C: #[results=[
C:   { id="spotify:track:0LThjFY2iTtNdd4wviwVV2"^^org.thingpedia.media-source:song("Permission to Dance"), artists=["spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX"^^org.thingpedia.media-source:artist("BTS")], album="spotify:album:1iLUfFVZF8bltkBkONumgG"^^org.thingpedia.media-source:album("Butter / Permission to Dance"), genres=["k-pop", "k-pop boy group"], release_date=new Date("2021-07-09T00:00:00.000Z"), popularity=95, energy=74.1, danceability=70.19999999999999, __device="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax") }
C: ]];
#! timestamp: 2021-08-03T19:02:35.367Z
A: Currently playing Permission to Dance.
AT: $dialogue @org.thingpedia.dialogue.transaction.sys_display_result;
#! timestamp: 2021-08-03T19:02:40.751Z
U: who is the artist
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: [artists] of @org.thingpedia.media-source(id="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax")).get_currently_playing();
#! timestamp: 2021-08-03T19:02:43.120Z
A: Did you mean get the artist of currently playing track?
A: Sorry, I had an error processing your command: Failed to compute a reply.
#! vote: down
#! timestamp: 2021-08-03T19:03:02.243Z
U: cancel
UT: $dialogue @org.thingpedia.dialogue.transaction.cancel;
C: $dialogue @org.thingpedia.dialogue.transaction.cancel;
C: @org.thingpedia.media-source(id="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax")).get_currently_playing()
C: #[results=[
C:   { id="spotify:track:0LThjFY2iTtNdd4wviwVV2"^^org.thingpedia.media-source:song("Permission to Dance"), artists=["spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX"^^org.thingpedia.media-source:artist("BTS")], album="spotify:album:1iLUfFVZF8bltkBkONumgG"^^org.thingpedia.media-source:album("Butter / Permission to Dance"), genres=["k-pop", "k-pop boy group"], release_date=new Date("2021-07-09T00:00:00.000Z"), popularity=95, energy=74.1, danceability=70.19999999999999, __device="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax") }
C: ]];
C: [artists] of @org.thingpedia.media-source(id="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax")).get_currently_playing()
C: #[results=[
C:   { id="spotify:track:0LThjFY2iTtNdd4wviwVV2"^^org.thingpedia.media-source:song("Permission to Dance"), artists=["spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX"^^org.thingpedia.media-source:artist("BTS")] }
C: ]];
#! timestamp: 2021-08-03T19:03:02.269Z
A: Alright, let me know if I can help you with anything else!
AT: $dialogue @org.thingpedia.dialogue.transaction.sys_end;
```

**Comment by tonyespinoza1** [comment]
this is beautiful.
