### ISSUE TITLE
Error 404 on Tutorial 1: Basic Sentence Generation

### ISSUE THREAD

**Issue by vivotan** [stanford-oval/genie-toolkit#684]
Hi,

refer https://github.com/stanford-oval/genie-toolkit/blob/master/doc/tutorial-basic.md

At Tutorial 1: Basic Sentence Generation, 

Step 1: Obtain the skill definitions

> You can retrieve the first two for a given skill from Thingpedia. For example, for the Bing skill, you can retrieve them from https://almond.stanford.edu/thingpedia/classes/by-id/com.bing. See the **Thingpedia documentation** for additional description of these files.

Page not found for https://almond.stanford.edu/thingpedia/developers/thingpedia-nl-support.md

Step 2: Obtain Parameter Datasets.

> You should then create a parameter-datasets.tsv file mapping a string type to a downloaded dataset file. A sample parameter-datasets.tsv can be found in **here**.

Page not found for https://github.com/stanford-oval/genie-toolkit/blob/master/test/data/parameter-datasets.tsv

**Comment by gcampax** [comment]
Hi! Thanks for your report.

It looks like the correct link is https://github.com/stanford-oval/genie-toolkit/blob/master/test/data/en-US/parameter-datasets.tsv
I'll fix it. 
I recommend you use the command-line tools to download the parameter datasets though, it will give you a file in the right format and download all available datasets at once.

**Comment by vivotan** [comment]
Hi, failed on the download-string-values command

Step 2: Obtain Parameter Datasets
> if you have an appropriate Thingpedia developer key, you can also download the datasets with:

> genie download-entity-values -d parameter-datasets/ --manifest parameter-datasets.tsv

100%  [==============================] - 184s 

> genie download-string-values -d parameter-datasets/ --manifest parameter-datasets.tsv --append-manifest

  0%  [..............................] - ETA: 0sHTTP request failed: {"error":"A valid developer key is required to download string datasets","code":"EPERM"}
/home/va-tutorials/genie-toolkit/dist/tool/genie.js:40
process.on('unhandledRejection', (up) => { throw up; });
                                                                     ^

HTTPError: Unexpected HTTP error 403 in request to https://thingpedia.stanford.edu/thingpedia/api/v3/strings/list/campusplan.kit.advanced:place?locale=en-US
    at IncomingMessage.<anonymous> (/home/va-tutorials/genie-toolkit/node_modules/thingpedia/dist/helpers/http.js:139:35)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 403,
  url: 'https://thingpedia.stanford.edu/thingpedia/api/v3/strings/list/campusplan.kit.advanced:place?locale=en-US',
  detail: '{"error":"A valid developer key is required to download string datasets","code":"EPERM"}'
}
- - - - 
I have the developer key from Thingpedia - User Profile, but how can i pass the developer key?

Thanks.

**Comment by gcampax** [comment]
You specify it on the command-line:
```
genie download-string-values --developer-key abcd...
```

Alternatively, you can set it once and for all in your git config:
```
git config --global thingpedia.developer-key abcd...
```

**Comment by vivotan** [comment]
Hi,

Step 3: Synthesize Sentences.

> genie generate --locale en-US --thingpedia thingpedia.tt --entities entities.json --dataset dataset.tt -o synthesized.tsv

  0%  [..............................] - ETA: 2323squery device_info(in req id : Entity(tt:device)
                  #_[canonical={
                    base=["name"],
                    passive_verb=["named #", "called #"]
                  }],
                  out help : String
                  #_[canonical={
                    base=["help", "documentation"]
                  }]
                  #[string_values="tt:long_free_text"],
                  out description : String
                  #_[canonical={
                    base=["description"]
                  }]
                  #[string_values="tt:long_free_text"],
                  out category : Enum(service, media, social_network, communication, home, health, data_management)
                  #_[canonical={
                    base=["category"],
                    adjective=["#"],
                    preposition=["in the # category"]
                  }],
                  out thingpedia_url : Entity(tt:url)
                  #_[canonical={
                    base=["thingpedia page", "thingpedia link"]
                  }],
                  out website : Entity(tt:url)
                  #_[canonical={
                    base=["website", "link", "url"]
                  }],
                  out issue_tracker : Entity(tt:url)
                  #_[canonical={
                    base=["issue tracking website", "bug report url"]
                  }])
#_[canonical="information about a device"]
#_[confirmation=""]
#_[formatted=[{
  type="rdl",
  displayTitle="${id}",
  webCallback="${thingpedia_url}"
}]]
#[confirm=false]
#[minimal_projection=["id"]]; id
Error expanding rule NT[projection_Any] -> the ${outParam} of ${table} (NT[outParam : out_param_Any], NT[table : with_filtered_table])
TypeError: Invalid field name id
    at resolveProjection (/home/va-tutorials/genie-toolkit/dist/lib/templates/ast_manip.js:381:19)
    at makeProjection (/home/va-tutorials/genie-toolkit/dist/lib/templates/ast_manip.js:399:83)
    at Object.makeSingleFieldProjection (/home/va-tutorials/genie-toolkit/dist/lib/templates/ast_manip.js:487:16)
    at /home/va-tutorials/genie-toolkit/dist/lib/templates/projections.genie.js:129:269
    at Function.combine (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/runtime.js:135:26)
    at Rule.apply (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/generator.js:83:37)
    at expandRuleSample (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/generator.js:1446:24)
    at expandRule (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/generator.js:1495:42)
    at SentenceGenerator.generate (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/generator.js:948:25)
    at /home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/batch.js:92:29
/home/va-tutorials/genie-toolkit/dist/tool/genie.js:40
process.on('unhandledRejection', (up) => { throw up; });
                                           ^

TypeError: Invalid field name id
    at resolveProjection (/home/va-tutorials/genie-toolkit/dist/lib/templates/ast_manip.js:381:19)
    at makeProjection (/home/va-tutorials/genie-toolkit/dist/lib/templates/ast_manip.js:399:83)
    at Object.makeSingleFieldProjection (/home/va-tutorials/genie-toolkit/dist/lib/templates/ast_manip.js:487:16)
    at /home/va-tutorials/genie-toolkit/dist/lib/templates/projections.genie.js:129:269
    at Function.combine (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/runtime.js:135:26)
    at Rule.apply (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/generator.js:83:37)
    at expandRuleSample (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/generator.js:1446:24)
    at expandRule (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/generator.js:1495:42)
    at SentenceGenerator.generate (/home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/generator.js:948:25)
    at /home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/batch.js:92:29
Emitted 'error' event on BasicSentenceGenerator instance at:
    at /home/va-tutorials/genie-toolkit/dist/lib/sentence-generator/batch.js:97:18

----

It happens on file thingpedia.tt line 364, need to add something like 

>#_[canonical=["id"]],
>out text : String

correct?

Thanks.

**Comment by gcampax** [comment]
The broken link has been fixed, closing.
