### ISSUE TITLE
Incorrect generation for sentences with example parameters in filter

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#75]
From the staging logs:
```
Aug 13 18:24:28 parmesan node[12097]: job 198: hey almond who got given name QUOTED_STRING_0 .
Aug 13 18:24:28 parmesan node[12097]: job 198: [object Object]
Aug 13 18:24:28 parmesan node[12097]: job 198: undefined
Aug 13 18:24:28 parmesan node[12097]: job 198: now => (@org.wikidata.person()), (id == x && P735 =~ __const_QUOTED__STRING_0) => notify;
Aug 13 18:24:28 parmesan node[12097]: job 198: TypeError: No variable x in schema, have P735,P734,P1477,P1449,P21,P27,P569,P570,P19,P20,P1196,P509,P119,P18,P109,P22,P25,P3373,P26,P40,P1971,P103,P106,P108,P39,P166,P1411,P69,P512,P551,P937,P102,P1576,P172,P140,P2048,P2067,P1853,P1050,P1429,P552,P410,P856,P737,P641,P54,P647,P1618,P286,P1344,P1830,P3828,P136,P264,P1303,P184,P185,P2002,P2003,P2013,P2847,P3265,P2397,P4265,P4411,P4013,P3984,id
Aug 13 18:24:28 parmesan node[12097]: job 198:     at ToNNConverter.valueToNN (/opt/thingengine/node_modules/thingtalk/lib/nn-syntax/tonn_converter.js:302:23)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at ToNNConverter.cnfFilterToNN (/opt/thingengine/node_modules/thingtalk/lib/nn-syntax/tonn_converter.js:430:155)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at ToNNConverter.tableToNN (/opt/thingengine/node_modules/thingtalk/lib/nn-syntax/tonn_converter.js:620:32)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at ToNNConverter.commandToNN (/opt/thingengine/node_modules/thingtalk/lib/nn-syntax/tonn_converter.js:747:46)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at ToNNConverter.programToNN (/opt/thingengine/node_modules/thingtalk/lib/nn-syntax/tonn_converter.js:801:29)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at ToNNConverter.toNN (/opt/thingengine/node_modules/thingtalk/lib/nn-syntax/tonn_converter.js:843:25)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at Object.toNN (/opt/thingengine/node_modules/thingtalk/lib/nn-syntax/index.js:34:22)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at BasicSentenceGenerator._output (/opt/thingengine/node_modules/genie-toolkit/lib/sentence-generator/index.js:527:33)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at BasicSentenceGenerator._minibatch (/opt/thingengine/node_modules/genie-toolkit/lib/sentence-generator/index.js:514:23)
Aug 13 18:24:28 parmesan node[12097]: job 198:     at _initialization.then (/opt/thingengine/node_modules/genie-toolkit/lib/sentence-generator/index.js:496:46)
```

**Comment by gcampax** [comment]
Is this bug still a thing? I haven't seen it in a while.

**Comment by rayslxu** [comment]
> Is this bug still a thing? I haven't seen it in a while.

Things have changed so much since it's reported, I would say let's close this and reopen if we see it appears again

**Comment by gcampax** [comment]
Fair.
