### ISSUE TITLE
Unexpected null in conversation logs timestamp

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#770]
From the logs of shared backend (this causes a crash):
```
HTTP request failed: {"error":"Error 1048: Column 'userTimestamp' cannot be null"}
Uncaught error in dialog loop HTTPError: Unexpected HTTP error 500 in request to http://dbproxy:8200/localtable/user_conversation/d4f49c5a-688b-40d6-aa41-d2c0580d3948
    at IncomingMessage.<anonymous> (/opt/almond-cloud/node_modules/thingpedia/lib/helpers/http.ts:174:35)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 500,
  url: 'http://dbproxy:8200/localtable/user_conversation/d4f49c5a-688b-40d6-aa41-d2c0580d3948',
  detail: `{"error":"Error 1048: Column 'userTimestamp' cannot be null"}`
}
```

**Comment by gcampax** [comment]
Turns out the column can indeed be null, and the cloud DB backend was fixed.
