### ISSUE TITLE
Catch cancellation errors when restoring conversation state

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#772]
See log:
```
Uncaught error in dialog loop CancellationError: User cancelled
    at ExecutionDialogueAgent._chooseDevice (/opt/almond-cloud/node_modules/genie-toolkit/lib/dialogue-agent/abstract_dialogue_agent.ts:304:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionDialogueAgent._prepareForExecution (/opt/almond-cloud/node_modules/genie-toolkit/lib/dialogue-agent/abstract_dialogue_agent.ts:265:17)
    at async ExecutionDialogueAgent.execute (/opt/almond-cloud/node_modules/genie-toolkit/lib/dialogue-agent/abstract_dialogue_agent.ts:144:13)
    at async ThingTalkDialogueHandler._executeCurrentState (/opt/almond-cloud/node_modules/genie-toolkit/lib/dialogue-agent/handlers/thingtalk.ts:443:81)
    at async DialogueLoop._initialize (/opt/almond-cloud/node_modules/genie-toolkit/lib/dialogue-agent/dialogue-loop.ts:469:27)
    at async DialogueLoop._loop (/opt/almond-cloud/node_modules/genie-toolkit/lib/dialogue-agent/dialogue-loop.ts:483:9) {
  code: 'ECANCELLED'
}
```

**Comment by gcampax** [comment]
This was solved at some point.
