### ISSUE TITLE
Broken skills can cause unrecoverable errors in dialogue state parsing

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#794]
Example:
```
Uncaught error in dialog loop ThingTalkSyntaxError: Parse error: unexpected token € in state 179, expected (,Any,ArgMap,Array,Boolean,Compound,Currency,Date,Entity,Enum,IDENTIFIER,Location,Measure,Number,Object,RecurrentTimeSpecification,String,Time,abstract,action,aggregate,all,any,as,asc,avg,await,beginDate,beginTime,bookkeeping,break,case,catch,class,compute,confirm,const,contains,contains~,continue,count,dataset,dayOfWeek,debugger,delete,desc,distance,do,edge,endDate,endTime,ends_with,entity,enum,error,export,extends,false,filter,finally,for,frequency,from,function,if,implements,import,in,in_array,in_array~,instanceof,interface,interval,join,language,let,list,max,min,mixin,monitor,monitorable,more,new,notify,now,null,of,on,oninput,opt,out,package,prefix_of,private,program,protected,public,query,req,results,return,set_time,sort,starts_with,static,stream,subtract,suffix_of,sum,super,switch,this,throw,true,try,typeof,var,void,while,with,yield,~contains,~in_array
    at ShiftReduceParser._helper (/opt/almond-cloud/node_modules/thingtalk/dist/utils/sr_parser_runtime.js:98:27)
    at ShiftReduceParser.parse (/opt/almond-cloud/node_modules/thingtalk/dist/utils/sr_parser_runtime.js:146:34)
    at Object.parse (/opt/almond-cloud/node_modules/thingtalk/dist/syntax_api.js:88:91)
    at Object.parse (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/utils/thingtalk/syntax.js:50:37)
    at ThingTalkDialogueHandler.initialize (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/dialogue-agent/handlers/thingtalk.js:456:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DialogueLoop._initialize (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:270:27)
    at async DialogueLoop._loop (/opt/almond-cloud/node_modules/genie-toolkit/dist/lib/dialogue-agent/dialogue-loop.js:282:9) {
  location: {
    start: { line: 20, column: 363, offset: 7539, token: 592 },
    end: { line: 20, column: 364, offset: 7540, token: 593 }
  }
}
```

This is caused by a bug in Yelp that doesn't parse correctly the price range marker from the API, but we should be more robust to it.
We should:
- add more validation of the output of ThingTalk programs to ensure they conform to the Thingpedia spec
- add robustness around restoring the conversation state, so we don't die in a loop

**Comment by gcampax** [comment]
We did both of the suggested changes.
