### ISSUE TITLE
Crash when recording a conversation

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#820]
If a command yields a cancellation from the agent (eg missing skill), we'll crash:
```
HTTP request failed: {"error":"Error 1048: Column 'userTimestamp' cannot be null"}
Uncaught error in dialog loop HTTPError: Unexpected HTTP error 500 in request to http://dbproxy:8200/localtable/user_conversation/1e6f6c62-9e82-4cc7-8ac5-b84a09a9b57d
    at IncomingMessage.<anonymous> (/opt/almond-cloud/node_modules/thingpedia/lib/helpers/http.ts:174:35)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 500,
  url: 'http://dbproxy:8200/localtable/user_conversation/1e6f6c62-9e82-4cc7-8ac5-b84a09a9b57d',
  detail: `{"error":"Error 1048: Column 'userTimestamp' cannot be null"}`
}
```

**Comment by gcampax** [comment]
Actually, null is a legitimate value and the table definition in almond-cloud is wrong.
