### ISSUE TITLE
Training of Genie-Toolkit

### ISSUE THREAD

**Issue by vinith-reddy25** [stanford-oval/genie-toolkit#867]
I ran the following command:

"$genie train --datadir <DATADIR> --outputdir <OUTPUTDIR> --workdir <WORKDIR> --config-file data/bert-lstm-single-sentence.json"

It is giving following error

"0% [..............................] - ETA: 0s/home/shishirkumar/genie-toolkit/dist/tool/genie.js:41
throw up;
^
Error: Command exited with code 2
at ChildProcess.<anonymous> (/home/shishirkumar/genie-toolkit/dist/lib/utils/process-utils.js:91:28)
at ChildProcess.emit (events.js:315:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)"

After adding "--debug", getting following error:

"
'genienlp' 'train' '--train_tasks' 'almond' '--save' '/home/shishirkumar/genie-toolkit/work_dir/model' '--cache' '/home/shishirkumar/genie-toolkit/work_dir/cache' '--data' '/home/shishirkumar/genie-toolkit/work_dir' '--preserve_case' '--no_commit' '--embeddings' '/home/shishirkumar/genie-toolkit/work_dir/embeddings' '--train_iterations' '100000' '--save_every' '2000' '--log_every' '500' '--val_every' '1000' '--train_batch_tokens' '4000' '--val_batch_size' '128' '--seq2seq_encoder' 'Identity' '--dimension' '768' '--rnn_dimension' '768' '--transformer_hidden' '768' '--transformer_layers' '0' '--rnn_layers' '2' '--rnn_zero_state' 'average' '--context_embeddings' 'bert-base-uncased@0' '--question_embeddings' 'bert-base-uncased@1' '--decoder_embeddings' '' '--trainable_encoder_embeddings' '0' '--trainable_decoder_embeddings' '25' '--transformer_lr_multiply' '0.5' '--train_context_embeddings' '--train_context_embeddings_after' '80000'
/home/shishirkumar/.local/lib/python3.8/site-packages/redis/connection.py:77: UserWarning: redis-py works best with hiredis. Please consider installing
warnings.warn(msg)
usage: genienlp [-h]
{train,export,predict,server,cache-embeddings,train-paraphrase,run-paraphrase,calibrate,transform-dataset,clean-paraphrasing-dataset,dialog-to-tsv,split-dataset,sts-calculate-scores,sts-filter,bootleg-dump-features,analyze-bootleg-results,oracle-vs-bootleg,kfserver,write-kf-metrics}
...
genienlp: error: unrecognized arguments: --seq2seq_encoder Identity --dimension 768 --transformer_hidden 768 --transformer_layers 0 --context_embeddings bert-base-uncased@0 --question_embeddings bert-base-uncased@1 --decoder_embeddings --trainable_encoder_embeddings 0 --transformer_lr_multiply 0.5 --train_context_embeddings --train_context_embeddings_after 80000
/home/shishirkumar/genie-toolkit/dist/tool/genie.js:41
throw up;
^

Error: Command exited with code 2
at ChildProcess.<anonymous> (/home/shishirkumar/genie-toolkit/dist/lib/utils/process-utils.js:91:28)
at ChildProcess.emit (events.js:315:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
"

**Comment by rayslxu** [comment]
This tutorial needs some updates. We will keep you posted once we have a newer version.
