### ISSUE TITLE
step 4 of tutorial 1

### ISSUE THREAD

**Issue by vinith-reddy25** [stanford-oval/genie-toolkit#868]
When I run 

"$genie augment synthesized.tsv --locale en-US --thingpedia thingpedia.tt --parameter-datasets parameter-datasets.tsv -o augmented.tsv"

I'm getting following error:

"
{
  id: '2000001006',
  flags: {
    replaced: false,
    augmented: false,
    contextual: false,
    synthetic: true,
    eval: false
  },
  preprocessed: 'is my QUOTED_STRING_0 light-bulb on or off',
  target_code: [
    '@org.thingpedia.iot.light-bulb ( name = QUOTED_STRING_0 ) . power ( ) ;'
  ]
}
[Error: SQLITE_ERROR: no such table: string] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
{
  id: '2000001006',
  flags: {
    replaced: false,
    augmented: false,
    contextual: false,
    synthetic: true,
    eval: false
  },
  preprocessed: 'is my QUOTED_STRING_0 light-bulb on or off',
  target_code: [
    '@org.thingpedia.iot.light-bulb ( name = QUOTED_STRING_0 ) . power ( ) ;'
  ]
}
[Error: SQLITE_ERROR: no such table: string] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
{
  id: '2000001006',
  flags: {
    replaced: false,
    augmented: false,
    contextual: false,
    synthetic: true,
    eval: false
  },
  preprocessed: 'is my QUOTED_STRING_0 light-bulb on or off',
  target_code: [
    '@org.thingpedia.iot.light-bulb ( name = QUOTED_STRING_0 ) . power ( ) ;'
  ]
}
[Error: SQLITE_ERROR: no such table: string] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
{
  id: '2000001006',
  flags: {
    replaced: false,
    augmented: false,
    contextual: false,
    synthetic: true,
    eval: false
  },
  preprocessed: 'is my QUOTED_STRING_0 light-bulb on or off',
  target_code: [
    '@org.thingpedia.iot.light-bulb ( name = QUOTED_STRING_0 ) . power ( ) ;'
  ]
}
[Error: SQLITE_ERROR: no such table: string] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
{
  id: '2000001006',
  flags: {
    replaced: false,
    augmented: false,
    contextual: false,
    synthetic: true,
    eval: false
  },
  preprocessed: 'is my QUOTED_STRING_0 light-bulb on or off',
  target_code: [
    '@org.thingpedia.iot.light-bulb ( name = QUOTED_STRING_0 ) . power ( ) ;'
  ]
}
[Error: SQLITE_ERROR: no such table: string] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
/home/vinith/Documents/genie-toolkit/dist/tool/genie.js:41
    throw up;
    ^

Error: SQLITE_ERROR: no such table: string
Emitted 'error' event on DatasetAugmenter instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at DatasetAugmenter.onerror (_stream_readable.js:754:7)
    at DatasetAugmenter.emit (events.js:314:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at DatasetAugmenter.afterTransform (_stream_transform.js:98:3)
    at /home/vinith/Documents/genie-toolkit/dist/lib/dataset-tools/augmentation/index.js:83:13 {
  errno: 1,
  code: 'SQLITE_ERROR'
}

"

**Comment by rayslxu** [comment]
This tutorial needs some updates. We will keep you posted once we have a newer version.
